- hosts: all
  become: 'yes'
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Download Long Term Jenkins release
      get_url:
        url: 'https://pkg.jenkins.io/redhat-stable/jenkins.repo'
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import jenkins key from url
      rpm_key:
        state: present
        key: 'https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key'
    - name: yum update
      yum:
        name: '*'
        state: latest
    - name: Install java (if aws java-17-amazon-corretto)
      yum:
        name: java-11-openjdk-devel
        state: present
    - name: Install jenkins
      yum:
        name: jenkins
        state: latest
    - name: Start jenkins
      service:
        name: jenkins
        state: started
    - name: Install Git
      yum:
        name: git
        state: latest
    - name: Download Maven3
      get_url:
        url: 'https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz'
        dest: /opt
