- hosts: all
  become: 'yes'
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: yum update
      yum:
        name: '*'
        state: latest
    - name: Install java (if aws java-17-amazon-corretto)
      yum:
        name: java-11-openjdk-devel
        state: present
    - name: Download Maven3
      get_url:
        url: 'https://download.sonatype.com/nexus/3/nexus-3.63.0-01-unix.tar.gz'
        dest: /opt
    - name: untar Maven3
      unarchive:
        src: /opt/nexus-3.63.0-01-unix.tar.gz
        dest: /opt
        remote_src: 'yes'
