- hosts: all
  remote_user: maravinth
  become: yes
  tasks:

  - name: install nginx
    yum:
         name: nginx
         state: installed

  - name: start nginx
    service:
         name: nginx
         state: started

  - name: copy file
    copy:
         src: /home/maravinth/test.html
         dest: /usr/share/nginx/html/test.html
         mode: "0777"
